#!/usr/bin/env bash
# Render the node-local .env.dspark (read by docker compose) from cluster.env.
# Usage: render-env.sh <head|worker>   — writes $KIT/.env.dspark
set -euo pipefail

ROLE="${1:?usage: render-env.sh <head|worker>}"
KIT="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
source "$KIT/cluster.env"

case "$ROLE" in
  head)   NODE_RANK=0; HEADLESS=;  VLLM_HOST_IP="$HEAD_R1" ;;
  worker) NODE_RANK=1; HEADLESS=1; VLLM_HOST_IP="$WORKER_R1" ;;
  *) echo "unknown role $ROLE" >&2; exit 1 ;;
esac

cat > "$KIT/.env.dspark" <<EOF
# GENERATED by render-env.sh ($ROLE) — edit cluster.env, not this file.
DSPARK_VLLM_IMAGE=$DSPARK_VLLM_IMAGE
DSPARK_MODEL=$DSPARK_MODEL
SERVED_MODEL_NAME=$SERVED_MODEL_NAME
HF_CACHE=$HF_CACHE
HF_HUB_OFFLINE=1
TRANSFORMERS_OFFLINE=1
VLLM_HOST=$VLLM_HOST
API_PORT=$API_PORT
MAX_MODEL_LEN=$MAX_MODEL_LEN
MAX_NUM_SEQS=$MAX_NUM_SEQS
MAX_NUM_BATCHED_TOKENS=$MAX_NUM_BATCHED_TOKENS
GPU_MEMORY_UTILIZATION=$GPU_MEMORY_UTILIZATION
MTP_NUM_TOKENS=$MTP_NUM_TOKENS
MASTER_ADDR=$MASTER_ADDR
MASTER_PORT=$MASTER_PORT
NODE_RANK=$NODE_RANK
HEADLESS=$HEADLESS
VLLM_HOST_IP=$VLLM_HOST_IP
NCCL_SOCKET_IFNAME=$NCCL_SOCKET_IFNAME
NCCL_IB_HCA=$NCCL_IB_HCA
NCCL_IB_GID_INDEX=$NCCL_IB_GID_INDEX
NCCL_CROSS_NIC=$NCCL_CROSS_NIC
NCCL_NET=$NCCL_NET
NCCL_IB_DISABLE=$NCCL_IB_DISABLE
EOF
chmod 600 "$KIT/.env.dspark"
echo "rendered $KIT/.env.dspark ($ROLE)"
